### ISSUE TITLE
Provide usage example?

### ISSUE THREAD

**Issue by fornasierov** [mnchl-kim/GRU-D-TF2#1]
Hello, first of all, thanks for the implementation using TF 2.0. 

Is there any way you could provide an example of model creation? Specifically, I'm trying to understand how to pass the input tensor to the GRUD in the right fashion. Maybe this is me, but I'm used to reading call argument info where the input shape is described as ["a 3D tensor, with shape `[batch, timesteps, feature]`" ](https://github.com/keras-team/keras/blob/v2.6.0/keras/layers/recurrent_v2.py#L204-L524). Could you please expand on your already explanatory comment "inputs -- shape: (N, (x, m, d, f), t, d)"?

**Comment by mnchl-kim** [comment]
GRU takes 3D tensor with shape [batch, timesteps, feature], in other words (N, t, d).
However, for GRU-D, it needs 4 information, which is observed value (x), masking (m), time interval (d), and last observed value (f).

Thus, 
observed value (x) -- shape: (N, t, d)
masking (m) -- shape: (N, t, d)
time interval (d) -- shape: (N, t, d)
last observed value (f) -- shape: (N, t, d)
=> with concatenation through new axis at 1, final inputs shape is (N, 4, t, d), which means (N, (x, m, d, f), t, d)

I did preprocess input data to follow above rule, so you also follow above convention or modify inputs parameter in call method.

**Comment by fornasierov** [comment]
Thanks for your explanation. I'm not sure about passing the last observed value. The preprocess I'm doing is as follows:

1. From multivariate time series X, create a mask M which has the same dimension as X and represents lack of observations as 0 and observations as 1;
2. From mask M, create time interval D which provides the time difference between observations (e.g., _m_ array [1,1,1,0,0,1,1,1] produces a _d_ array [0,1,1,1,1,3,1,1]). My original dataset provide 1 day interval between observations, so that's why most deltas are 1;
3. Concatenation of all observations: (N, (_x_, _m_, _d_), _t_, _d_).

I was unaware of the need to provide _f_. In order to do so, do you suggest I just add one value (like a 0) to the beginning of the X array, or is there a better way to do that?

**Comment by mnchl-kim** [comment]
[x_hat = gamma_x * f + (1 - gamma_x) * self.inputs_mean](https://github.com/mnchl-kim/GRU-D-TF2/blob/3cfe440002bc6f020076bda4e15212b5146d7b8a/models.py#L86)

To calculate x_hat for missing imputation, the last observed value is needed.

For example, with your case,
x = [x0, x1, x2, NAN, NAN, x5, x6, x7]
m = [1, 1, 1, 0, 0, 1, 1, 1]
d = [0, 1, 1, 1, 1, 3, 1, 1]

x3_hat = gamma_x * x2 + (1 - gamma_x) * x_mean
x4_hat = gamma_x * x2 + (1 - gamma_x) * x_mean

In that case, at time point x3 and x4, there is no way to give the information about last observed value, at least I think.
So I made a forward vector additionally, such as
f = [x*, x0, x1, x2, x2, x2, x5, x6]
(The first value x* is not described in original paper, so I put x_mean on x*.)

**Comment by fornasierov** [comment]
Ok, I will test adding a value to the beginning of _x_ to create the forward vector. Additionally, I will try providing the last known observation to the forward vector to see what happens. To summarize, there will be two scenarios:

1. _f_ vector will be _x_ shifted to the right with the addition of _x*_ at the beginning;
2. Same as 1 when there are consecutive observations. When there are no observations, the last known value will be passed forward until a new observation appears (similar to 'ffill' function for pandas).

I will come back with the results of the experiment, thus closing the issue. For now, thank you for the attention.

**Comment by fornasierov** [comment]
I was able to preprocess the data following your comments. I'm closing the issue. Thanks, @mnchl-kim.
